## Since the yfinance libary is vital for collecting data, I find it necessary to learn the foundations of this libary

In [3]:
import yfinance as yf

In [ ]:
## saving a stock as ticker
ticker = yf.Ticker("AAPL")

In [ ]:
## a great way of reading docs
??yf.Ticker

In [11]:
ticker.info["forwardPE"]

35.582424

In [19]:
ticker.analyst_price_targets

{'current': 341.07,
 'high': 405.0,
 'low': 215.0,
 'mean': 328.22205,
 'median': 340.0}

In [ ]:
ticker.quarterly_balance_sheet

In [ ]:
ticker.calendar

In [26]:
df = ticker.history(period="6d")

In [27]:
price = df["Close"]

In [ ]:
ticker.options

In [ ]:
ticker.option_chain(ticker.options[0]).calls

### Now we go to an index

In [40]:
yf.Ticker("QQQ").funds_data.sector_weightings

{'realestate': 0.0,
 'consumer_cyclical': 0.111099996,
 'basic_materials': 0.01,
 'consumer_defensive': 0.0624,
 'technology': 0.59150004,
 'communication_services': 0.127,
 'financial_services': 0.0021,
 'utilities': 0.0114,
 'industrials': 0.039100002,
 'energy': 0.0053,
 'healthcare': 0.0402}

In [41]:
yf.Tickers(["AAPL","GOOG","MSFT"]).history()

[*********************100%***********************]  3 of 3 completed

Price            Close                         Dividends             \
Ticker            AAPL        GOOG        MSFT      AAPL  GOOG MSFT
Date
2026-08-26  313.450012  338.880005  496.369995       0.0  0.00  0.0
2026-08-27  314.579987  337.490875  505.059998       0.0  0.00  0.0
2026-08-28  319.700012  342.657532  513.530029       0.0  0.00  0.0
2026-08-31  316.850006  335.192383  507.290009       0.0  0.00  0.0
2026-09-01  325.130005  331.814575  501.019989       0.0  0.00  0.0
2026-09-02  324.959991  333.563446  496.820007       0.0  0.00  0.0
2026-09-03  328.209991  338.859985  510.119995       0.0  0.00  0.0
2026-09-04  319.970001  335.309998  499.700012       0.0  0.22  0.0
2026-09-08  316.220001  335.380005  493.950012       0.0  0.00  0.0
2026-09-09  315.339996  328.380005  491.649994       0.0  0.00  0.0
2026-09-10  326.570007  330.390015  492.440002       0.0  0.00  0.0
2026-09-11  332.269989  335.450012  495.630005       0.0  0.00  0.0
2026-09-14  333.079987  345.709991  505.410004       0.0  0.00  0.0
2026-09-15  331.339996  341.429993  497.119995       0.0  0.00  0.0
2026-09-16  332.410004  339.359985  490.299988       0.0  0.00  0.0
2026-09-17  337.000000  343.679993  497.750000       0.0  0.00  0.0
2026-09-18  336.130005  344.410004  493.779999       0.0  0.00  0.0
2026-09-21  338.980011  350.869995  501.609985       0.0  0.00  0.0
2026-09-22  339.750000  347.410004  498.000000       0.0  0.00  0.0
2026-09-23  337.019989  334.980011  500.589996       0.0  0.00  0.0
2026-09-24  335.920013  339.010010  497.929993       0.0  0.00  0.0
2026-09-25  341.070007  341.079987  516.169983       0.0  0.00  0.0

Price             High                                 Low  ...              \
Ticker            AAPL        GOOG        MSFT        AAPL  ...        MSFT
Date                                                        ...
2026-08-26  315.429993  342.968354  497.399994  308.799988  ...  487.309998
2026-08-27  315.399994  338.590168  506.480011  309.399994  ...  490.079987
2026-08-28  322.369995  345.205865  517.780029  315.450012  ...  504.869995
2026-08-31  321.239990  340.408997  512.190002  312.799988  ...  506.390015
2026-09-01  327.299988  333.733343  505.970001  314.730011  ...  496.779999
2026-09-02  328.399994  336.291686  500.269989  323.529999  ...  493.809998
2026-09-03  330.809998  340.628856  515.650024  324.109985  ...  500.799988
2026-09-04  328.929993  340.179993  511.000000  317.859985  ...  499.359985
2026-09-08  320.700012  336.480011  495.190002  314.899994  ...  490.149994
2026-09-09  319.149994  329.339996  494.390015  309.899994  ...  489.799988
2026-09-10  326.739990  330.890015  494.519989  316.510010  ...  486.000000
2026-09-11  336.220001  339.950012  498.970001  326.299988  ...  492.579987
2026-09-14  335.500000  346.450012  509.950012  331.339996  ...  495.339996
2026-09-15  331.779999  344.359985  505.899994  328.350006  ...  495.540009
2026-09-16  335.480011  344.700012  495.970001  330.700012  ...  487.230011
2026-09-17  338.339996  345.964996  501.470001  330.179993  ...  493.170013
2026-09-18  338.489990  355.130005  498.649994  332.529999  ...  491.100006
2026-09-21  339.640015  353.299988  501.869995  333.049988  ...  491.329987
2026-09-22  345.339996  359.980011  508.500000  338.750000  ...  493.649994
2026-09-23  341.799988  346.329987  509.440002  335.500000  ...  495.880005
2026-09-24  338.910004  339.309998  498.899994  334.299988  ...  491.220001
2026-09-25  341.670013  343.600006  519.400024  334.529999  ...  497.250000

Price             Open                         Stock Splits            \
Ticker            AAPL        GOOG        MSFT         AAPL GOOG MSFT
Date
2026-08-26  310.299988  342.957344  487.850006          0.0  0.0  0.0
2026-08-27  310.549988  336.081786  494.880005          0.0  0.0  0.0
2026-08-28  316.850006  337.390932  505.329987          0.0  0.0  0.0
2026-08-31  319.600006  339.799377  510.380005          0.0  0.0  0.0
2026-09-01  316.980011  332.034434  497.519989          0.0  0.0  0.0
2026-09-02  326.869995  330.555389  499.850006          0.0  0.0  0.0
2026-09-03  324.869995  336.291676  501.660004          0.0  0.0  0.0
2026-09-04  328.309998  339.179993  510.000000          0.0  0.0  0.0
2026-09-08  317.100006  331.989990  493.010010          0.0  0.0  0.0
2026-09-09  315.489990  329.119995  493.070007          0.0  0.0  0.0
2026-09-10  316.670013  326.079987  488.320007          0.0  0.0  0.0
2026-09-11  327.450012  332.730011  495.649994          0.0  0.0  0.0
2026-09-14  334.790009  339.109985  497.059998          0.0  0.0  0.0
2026-09-15  330.140015  343.339996  500.059998          0.0  0.0  0.0
2026-09-16  332.529999  343.359985  493.029999          0.0  0.0  0.0
2026-09-17  334.769989  345.000000  497.799988          0.0  0.0  0.0
2026-09-18  337.910004  351.220001  497.970001          0.0  0.0  0.0
2026-09-21  335.279999  346.190002  494.950012          0.0  0.0  0.0
2026-09-22  340.140015  353.239990  507.320007          0.0  0.0  0.0
2026-09-23  341.079987  346.299988  500.760010          0.0  0.0  0.0
2026-09-24  336.720001  333.000000  495.070007          0.0  0.0  0.0
2026-09-25  336.040009  338.924988  499.040009          0.0  0.0  0.0

Price         Volume
Ticker          AAPL      GOOG      MSFT
Date
2026-08-26  34024500  16176400  20758900
2026-08-27  32419200  17936100  28688800
2026-08-28  38649400  17841900  29207300
2026-08-31  41242700  23202000  27208900
2026-09-01  53167400  16313400  21046900
2026-09-02  33776400  12995900  15336100
2026-09-03  37225800  12858300  24125900
2026-09-04  39606900  12700500  18101800
2026-09-08  35477100  14150300  18882300
2026-09-09  65640000  19326900  12889600
2026-09-10  70011900  16418900  16038800
2026-09-11  50716900  15820700  14510500
2026-09-14  39269100  22484400  23091900
2026-09-15  31748200  13361000  17794600
2026-09-16  35981000  12869700  16670300
2026-09-17  36700200  15315700  17841600
2026-09-18  86588200  34108900  39622300
2026-09-21  34999200  18252200  27959900
2026-09-22  40711800  20165100  21652800
2026-09-23  31658800  23283400  19445600
2026-09-24  24733100  15965000  16657600
2026-09-25  29950100  13835100  38154200

[22 rows x 21 columns]

In [42]:
yf.download(["AAPL", "MSFT"])

[*********************100%***********************]  2 of 2 completed

Price            Close                    High                     Low  \
Ticker            AAPL        MSFT        AAPL        MSFT        AAPL
Date
2026-08-26  313.450012  496.369995  315.429993  497.399994  308.799988
2026-08-27  314.579987  505.059998  315.399994  506.480011  309.399994
2026-08-28  319.700012  513.530029  322.369995  517.780029  315.450012
2026-08-31  316.850006  507.290009  321.239990  512.190002  312.799988
2026-09-01  325.130005  501.019989  327.299988  505.970001  314.730011
2026-09-02  324.959991  496.820007  328.399994  500.269989  323.529999
2026-09-03  328.209991  510.119995  330.809998  515.650024  324.109985
2026-09-04  319.970001  499.700012  328.929993  511.000000  317.859985
2026-09-08  316.220001  493.950012  320.700012  495.190002  314.899994
2026-09-09  315.339996  491.649994  319.149994  494.390015  309.899994
2026-09-10  326.570007  492.440002  326.739990  494.519989  316.510010
2026-09-11  332.269989  495.630005  336.220001  498.970001  326.299988
2026-09-14  333.079987  505.410004  335.500000  509.950012  331.339996
2026-09-15  331.339996  497.119995  331.779999  505.899994  328.350006
2026-09-16  332.410004  490.299988  335.480011  495.970001  330.700012
2026-09-17  337.000000  497.750000  338.339996  501.470001  330.179993
2026-09-18  336.130005  493.779999  338.489990  498.649994  332.529999
2026-09-21  338.980011  501.609985  339.640015  501.869995  333.049988
2026-09-22  339.750000  498.000000  345.339996  508.500000  338.750000
2026-09-23  337.019989  500.589996  341.799988  509.440002  335.500000
2026-09-24  335.920013  497.929993  338.910004  498.899994  334.299988
2026-09-25  341.070007  516.169983  341.670013  519.400024  334.529999

Price                         Open                Volume
Ticker            MSFT        AAPL        MSFT      AAPL      MSFT
Date
2026-08-26  487.309998  310.299988  487.850006  34024500  20758900
2026-08-27  490.079987  310.549988  494.880005  32419200  28688800
2026-08-28  504.869995  316.850006  505.329987  38649400  29207300
2026-08-31  506.390015  319.600006  510.380005  41242700  27208900
2026-09-01  496.779999  316.980011  497.519989  53167400  21046900
2026-09-02  493.809998  326.869995  499.850006  33776400  15336100
2026-09-03  500.799988  324.869995  501.660004  37225800  24125900
2026-09-04  499.359985  328.309998  510.000000  39606900  18101800
2026-09-08  490.149994  317.100006  493.010010  35477100  18882300
2026-09-09  489.799988  315.489990  493.070007  65640000  12889600
2026-09-10  486.000000  316.670013  488.320007  70011900  16038800
2026-09-11  492.579987  327.450012  495.649994  50716900  14510500
2026-09-14  495.339996  334.790009  497.059998  39269100  23091900
2026-09-15  495.540009  330.140015  500.059998  31748200  17794600
2026-09-16  487.230011  332.529999  493.029999  35981000  16670300
2026-09-17  493.170013  334.769989  497.799988  36700200  17841600
2026-09-18  491.100006  337.910004  497.970001  86588200  39622300
2026-09-21  491.329987  335.279999  494.950012  34999200  27959900
2026-09-22  493.649994  340.140015  507.320007  40711800  21652800
2026-09-23  495.880005  341.079987  500.760010  31658800  19445600
2026-09-24  491.220001  336.720001  495.070007  24733100  16657600
2026-09-25  497.250000  336.040009  499.040009  29950100  38154200